version: '3.9'

services:
  consul:
    container_name: consul
    image: hashicorp/consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - '8500:8500'
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - '1880:1880'
    volumes:
      - ./data-nodered:/data-nodered
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: mysql
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 3306
      MB_DB_USER: root
      MB_DB_PASS: root123!!
      MB_DB_HOST: host.docker.internal
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5