version: '3'

services:
  consul:
    container_name: consul
    image: hashicorp/consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - '8500:8500'
  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - '1880:1880'
    volumes:
      - ./data-nodered:/data-nodered