version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: sandbox
      MYSQL_USER: sandbox_user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './data/mariadb/data:/var/lib/mysql'
      - './data/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './data/mariadb/sql:/docker-entrypoint-initdb.d'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
