version: '3.8'

services:
  mage:
    image: mageai/mageai:latest
    container_name: mage
    command: mage start mage_project
    ports:
      - "6789:6789"
    volumes:
      - ./mage_project:/home/src/mage_project
    environment:
      - USER_CODE_PATH=/home/src/mage_project
    restart: unless-stopped
